### ISSUE TITLE
Request: add Actions to frequently used command

### ISSUE THREAD

**Issue by Nstd** [WahdanZ/SpockAdb#22]
The "Open Current Activity" command may be frequently used, If there's a related Action, we can bind a shortcuts to it.

**Comment by WahdanZ** [comment]
I agree with you, I will consider it in the upcoming release

**Comment by WahdanZ** [comment]
add in the latest version

**Comment by Nstd** [comment]
@WahdanZ Hi, after I update to v2.0.0, I can't open any activity now. And I got this exception: 
![image](https://user-images.githubusercontent.com/3004225/117240045-8f59ff00-ae62-11eb-89a6-337f557a05ae.png)
part ① is my packageName
part ② is the target Activity class name

Here is my AS version: 
![image](https://user-images.githubusercontent.com/3004225/117240175-dd6f0280-ae62-11eb-81a7-ff48fa018068.png)

**Comment by WahdanZ** [comment]
can you told me also the android version on the device or emulator you used

**Comment by Nstd** [comment]
> can you told me also the android version on the device or emulator you used

device: realme x50 / RMX 2051 / realme UI v1.0
android 10

**Comment by WahdanZ** [comment]
okay thanks, can you also confirm it happened with this project only or all projects you have

**Comment by Nstd** [comment]
> okay thanks, can you also confirm it happened with this project only or all projects you have

I check the command result of `dumpsys activity activities | grep mResumedActivity` : 
``` java
    mResumedActivity: ActivityRecord{e83a9d3 u0 com.haizitong.hzt.yuan/com.haizitong.minhang.codes.ui.activity.account.ActLoginMain2 t1229}
```

And I guess your test activity name in AndroidManifest.xml is not in full path, such as `com.a.b/.MyActivity` ?
So you just remove the char `/`
https://github.com/WahdanZ/SpockAdb/blob/a08aa1832faf75f4a48d5493722f9724f78cf793/src/main/kotlin/spock/adb/command/GetActivityCommand.kt#L17

But while in my app, all activities are name in full path.

**Comment by WahdanZ** [comment]
oh good nice catch,
I'll fix this during my weekend, also you can create PR to fix this if you have enough time

**Comment by Nstd** [comment]
> oh good nice catch,
> I'll fix this during my weekend, also you can create PR to fix this if you have enough time

I fix it and send the PR. You can check it later.

**Comment by WahdanZ** [comment]
thanks

**Comment by Nstd** [comment]
> thanks

It's my pleasure. 😄 

And I find another problem, the `Open Current Fragment` is no use.

Here's my `dumpsys` log:

[log2.log](https://github.com/WahdanZ/SpockAdb/files/6438643/log2.log)

**Comment by Nstd** [comment]
> > thanks
> 
> It's my pleasure. 😄
> 
> And I find another problem, the `Open Current Fragment` is no use.
> 
> Here's my `dumpsys` log:
> 
> [log2.log](https://github.com/WahdanZ/SpockAdb/files/6438643/log2.log)

@WahdanZ Will you paste the log which dumps from your app? Maybe our log is diffrent.

**Comment by Nstd** [comment]
Hi @WahdanZ , I made a fix of `Open Current Fragment` is no use. And I don't know if the fix is fit your app or not. Please check it.
