### ISSUE TITLE
Open Current App BackStack does not open selected activity

### ISSUE THREAD

**Issue by mgoyanes** [WahdanZ/SpockAdb#33]
When I press the "Open Current App BackStack " command it shows me this:

![image](https://user-images.githubusercontent.com/5049948/139698366-f14bd91d-d483-45bd-863f-9c8d3ac2a175.png)

Those are in fact my app activities, but after I click in the activity, the activity file does not open.
This is due to the activity package isn't correctly obtained.
In the example, `getCurrentRunningActivities(shellOutputReceiver.toString())` returns:

![image](https://user-images.githubusercontent.com/5049948/139698070-f0b2c075-6ca5-469f-abc3-b906411ffb04.png)

As you can see, the activity is incorrect since it shows `activity=com.android.example.livedatacom.android.example.livedatabuilder.LiveDataActivity` where it should be `activity=com.android.example.livedatabuilder.LiveDataActivity`

The following patch solves this issue. I didn't create a PR since I don't know how the fragment handling is supposed to show on the screen.
[open activity.log](https://github.com/WahdanZ/SpockAdb/files/7454414/open.activity.log) (rename to patch)

**Comment by Nstd** [comment]
The lateset version is fixed.
