### ISSUE TITLE
Request: allow to choose which buttons to show and which not to show

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [WahdanZ/SpockAdb#9]
As the title says.

**Comment by WahdanZ** [comment]
fix in the latest version

**Comment by AndroidDeveloperLB** [comment]
Can you please demonstrate?

**Comment by WahdanZ** [comment]
in the latest version, you have dialog to show and hide buttons 
![image](https://user-images.githubusercontent.com/4412251/116941026-337b5480-ac6f-11eb-9a1d-2a42cf63d92d.png)

**Comment by AndroidDeveloperLB** [comment]
Oh ok thank you!
